### ISSUE TITLE
Mock up of searching for projects in use by multiple Brigades

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/brigade#380] opened 2015-10-29 04:51 UTC
#### Description

On the Brigade [Project Search page](http://www.codeforamerica.org/brigade/projects) we want to easily find projects that are being worked on by multiple Brigades. It has been requested [here](https://github.com/codeforamerica/brigade/issues/346#issuecomment-148114578) and [here](https://github.com/codeforamerica/brigade/issues/371).

The most confusing part is probably figuring out the right formula for forked projects. There's a few ways you could do it:
1. Just show projects with a high `forks_count`.
2. Show projects that appear under lots of different Brigade project lists.
3. Show projects that are tagged as good for many Brigades.
#### Help Wanted

We want a mock up of what this may look like or how the flow for filtering could go.

**Comment by tdooner** [comment] 2017-11-17 18:35
dupe of #379

**Closed by tdooner** 2017-11-17 18:35 UTC
Labels: enhancement, help wanted
